version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/third_party/"
  ignore:
  # dependabot doesn't support upgrading to tagged versions only, disable fmt to reduce noise
  - dependency-name: "fmt"
  schedule:
    interval: weekly
    # UTC
    time: "08:00"
